// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAavFQ8vU0vWRfLqV8ZSxoLe9RAn2C6Yhg',
    appId: '1:491665723369:web:380a8dbae4397cebe48578',
    messagingSenderId: '491665723369',
    projectId: 'fir-123-16cef',
    authDomain: 'fir-123-16cef.firebaseapp.com',
    storageBucket: 'fir-123-16cef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8y98hDZlNcTp5FbfztfGTfZeoumD3eok',
    appId: '1:491665723369:android:c14b6659764d9d71e48578',
    messagingSenderId: '491665723369',
    projectId: 'fir-123-16cef',
    storageBucket: 'fir-123-16cef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgYG1hQT_inJuokgb5fcEsQwuP959fAyk',
    appId: '1:491665723369:ios:f7e9c8f6fe20da54e48578',
    messagingSenderId: '491665723369',
    projectId: 'fir-123-16cef',
    storageBucket: 'fir-123-16cef.firebasestorage.app',
    iosBundleId: 'com.example.firebase123',
  );
}
